### ISSUE TITLE
Metadata statistic portal

### ISSUE THREAD

**Issue by dpastorgalan** [Jollyfant/PMAG2#45]
Statistics portal creates automatically geographic metadata when you combine sites, how does it do it? Wouldn't it be a good policy to allow the user to be able to define group "metadata" that goes together with the core metadata? That would allow being able to set the coordinates of locality combining several sites without losing the core metadata, and at the same time allowing to choose where to show the parachutes in the map.
Perhaps with a pop-up when you combine sites suggesting group metadata? Maybe the group metadata may include a comment in which you explain briefly why you merged collections, example: "two flanks of the same fold separated by 2 km same component, grouped to obtain a better pole with 50 cores"

**Comment by Jollyfant** [comment]
It works like this:

Each direction has individual metadata (latitude, longitude). When you select a single collection on the map it takes the average latitude, longitude of all directions in that collection (also ages) and puts it on the map.

If you combine two collections to form a single collection it will just include all directions. Therefore, it will take the average geographic location of all directions.

If you want to edit the metadata manually you can export it using `key e`. That will copy the directions to your clipboard. You can paste this in Excel and replace whatever you want then load it as a new site.

Editing metadata is tricky because now every direction has everything.. and I don't wanna implement the functionality of something like Excel in the website.

**Comment by dpastorgalan** [comment]
Ok! It is fair. Maybe we should explain that somewhere.

Also, I did not want some editing functionality like table style. It was more like when you combine several groups a pop-up menu ask you if you want to keep the cut-off samples and if you want to mirror the site etc. I meant that in such window, in addition it could tell you: This is the latitude the software will give to the new collection, and there, if you edit it you get a "collection" latitude BUT the per specimen latitude will remain original. I that way whatever you share keeps all the info.

**Comment by Jollyfant** [comment]
Yeah I get what you're saying but if you want to do that you should export to Excel and modify values there. Because for latitude, longitude I could do it.. but then someone wants age.. and another person wants level.. and then we end up with a monstrous input window. I prefer to keep it clean!

**Comment by dpastorgalan** [comment]
Fair enough! I think it is a perfectly fine option but then I think we should add some text somewhere explaining that `key e` you get an editable file in which you can modify any parameters that become different when merging, like coordinates, level or age...
