### ISSUE TITLE
Bedding - Core orientation - Interpretation portal

### ISSUE THREAD

**Issue by dpastorgalan** [Jollyfant/PMAG2#70]
If you change the bedding or core orientation in the interpretation portal, the interpreted directions disappear. And you have to re-do it again.

This is especially a pain after finding a consistent mistake (i.e. forgot to apply declination correction or applied a wrong one) after analyzing all the collection.

Can this be changed to keep the interpretation?

**Comment by Jollyfant** [comment]
Unfortunately not.. since interpretations are locked to rotated coordinates. If the core/bedding orientation changes it has to be deleted. Of course it's possible to re-do the intepretation automatically with the same steps, but not worth it IMHO.

The steps should still be selected. So change the bedding and hit `1` to make the interpretation appear again!
